CREATE DATABASE IF NOT EXISTS BookStoreDB;
USE BookStoreDB;
CREATE TABLE authors(
    AuthorID INT AUTO_INCREMENT PRIMARY KEY,
    AuthorName VARCHAR(100) NOT NULL,   
    Country VARCHAR(100) NOT NULL,
);
CREATE TABLE books(
    BookID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(200) NOT NULL,
    Price DECIMAL(10, 2) NOT NULL,
    AuthorID INT NOT NULL
); 

 